### PR TITLE
Feature/implement missing features

### PR DESCRIPTION
**Pull request by michaelnico**
### Scenarios to be tested:
* Sending a Fax with Timezone in FaxMessage.
* Sending a Fax with Timezone in SendFaxRequest.
* Sending a Fax with DocumentRef.
* Sending a Fax with FaxDitheringTechnique.
* Sending a Fax with MustBeSentBeforeDate in FaxMessage.
* Sending a Fax with MustBeSentBeforeDate in SendFaxRequest.
* Sending a Fax with MaxFaxPages in FaxMessage.
* Sending a Fax with MaxFaxPages in SendFaxRequest.
* Sending a Fax with CLI in FaxMessage
* Sending a Fax with CLI in SendFaxRequest
*  Sending a Fax with SendFrom in FaxMessage
* Sending a Fax with SendFrom in SendFaxRequest
* Sending a Fax with Resolution in SendFaxRequest
* Sending a Fax with Resolution in FaxMessage
* Sending a Fax with Blocklists in FaxMessage
* Sending a Fax with Blocklists in SendFaxRequest
* Sending a Fax with DocMergeData
* Sending a Fax with ScheduledStartTime in FaxMessage
* Sending a Fax with ScheduledStartTime in SendFaxRequest
* Sending a Fax with retries in FaxMessage
* Sending a Fax with retries in SendFaxRequest
* Sending a Fax with BusyRetries in FaxMessage
* Sending a Fax with BusyRetries in SendFaxRequest
* Sending a Fax with HeaderFormat in FaxMessage
* Sending a Fax with HeaderFormat in SendFaxRequest
* Send FaxStatusrRequest
* Send Resume fax request
* Send Stop fax request
* Send SavedFaxDocument request
* Send FaxDocumentPreview request
* Send DeleteFaxDocument request
* Send StampMerge requests (StampMergeFieldTextValue & StampMergeFieldImageValue)

Thanks,
Michael

### CODE REVIEW

**Comment by edwardGolez** [comment]
Hi @michaelnico.
I'm getting back on this on. Sorry for the wait. :sob:

**Comment by edwardGolez** [comment]
**1. Save Fax Document** :ok_hand: 

**2. Fax Document Preview**
 * simple  :ok_hand: 
 * text stamp merge -> add space between `fontName` and `fontSize` in `<ImageValue>` tag
 * image stamp merge  :ok_hand: : 
 * document merge  :ok_hand: 

**3. Delete Fax Document** 
 * marshalling `<MessageRefs>` seem to have a problem
messagerefs in delete fax document request

<hr/>
*** Not yet done, will be adding more comments for other endpoints ***

**Comment by michaelnico** [comment]
hi @edwardGolez, 

#### Fax Document Preview

- Added space between the fontName and fontSize in TextValue tag.

#### Delete Fax Document
 
- Multiple deletion of messagRefs is removed because it is intended for internal usage only.

Thanks,
Michael

**Review by edwardGolez — APPROVED** [review]
Hi @michaelnico !!

I think this already works fine for all types of messages.

One question: Should we leave the production beta pointing to v2.2 instead of v2.1?

mpenv



Thanks,
Pool

**Comment by michaelnico** [comment]
Hi @edwardGolez, 

Sorry about the endpoint version, I updated the endpoint of PRODUCTION_BETA.

Thanks,
Michael

**Pull request merged**
